# Testing BACKEND2 
GET http://127.0.0.1:8000/api/products/
###
# Testing BACKEND1
GET http://127.0.0.1:8000/admin/

###

# Testing UserAddressesListView
GET http://127.0.0.1:8000/account/all-address-details/

###
### Register a new user
POST http://localhost:8000/account/register/
Content-Type: application/json

{
    "username": "test",
    "email": "test@example.com",
    "password": "test"
}

###
### Login a user
POST http://localhost:8000/account/login/
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
###